<?php

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.delfi.lt/login/v2/graphql');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "$'{n");
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Authority: api.delfi.lt';
$headers[] = 'Accept: */*';
$headers[] = 'Accept-Language: en-GB,en;q=0.9';
$headers[] = 'Cache-Control: no-cache';
$headers[] = 'Content-Type: application/json';
// $headers[] = 'Cookie: adxadid=8db4a5b5-8dc3-4fd5-8c9a-a27326b28493; _ga=GA1.2.1723807308.1661792468; _gid=GA1.2.1001741130.1661792468; _fbp=fb.1.1661792468089.1837007838; __gfp_64b=tDdxhyaj.6PWG_1I.zeft7_RZPBg_oLVqQugsYoE2YT.T7|1661792467; dcid=2020263534,1,1693328469,1661792469,de9ee98caddedf599a93ad5f2f0eca1d; _pprv=%7B%22consent%22%3A%7B%220%22%3A%7B%22mode%22%3A%22opt-in%22%7D%2C%221%22%3A%7B%22mode%22%3A%22opt-in%22%7D%2C%222%22%3A%7B%22mode%22%3A%22opt-in%22%7D%2C%223%22%3A%7B%22mode%22%3A%22opt-in%22%7D%2C%224%22%3A%7B%22mode%22%3A%22opt-in%22%7D%2C%225%22%3A%7B%22mode%22%3A%22opt-in%22%7D%2C%226%22%3A%7B%22mode%22%3A%22opt-in%22%7D%2C%227%22%3A%7B%22mode%22%3A%22opt-in%22%7D%7D%7D; _pctx=%7Bu%7DN4IgDghg5gpgagSxgdwJIBMQC4QBsDsAZgAwBGyAjAPYDWAxgG74B2ALLnSADQgCuAzjABO-bM165cPAcIDKAFwjyB2EBGZVm3EPwTyYGVRQqsATAE4AbOeLnzAZlYUArNeLWQAXyA; cX_S=l7f0bwa53osdtalq; _pcid=%7B%22browserId%22%3A%22l7f0bw1od1w11xdp%22%7D; cX_P=l7f0bw1od1w11xdp; cX_partner=adform%3D2; cX_G=cx%3A2hnsh6fnz9226w6z2lwxqrswv%3A1iy0643arhhxz';
$headers[] = 'Origin: https://www.delfi.lt';
$headers[] = 'Pragma: no-cache';
$headers[] = 'Referer: https://www.delfi.lt/';
$headers[] = 'Sec-Ch-Ua: \"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"';
$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
$headers[] = 'Sec-Ch-Ua-Platform: \"macOS\"';
$headers[] = 'Sec-Fetch-Dest: empty';
$headers[] = 'Sec-Fetch-Mode: cors';
$headers[] = 'Sec-Fetch-Site: same-site';
$headers[] = 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);