version: "3.9"

services:
  nginx:
    image: nginx:1.23.1
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8085:80

  php:
    image: php:8.1.1-fpm-alpine3.15
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    # tty: true