<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><?php echo env('APP_NAME', 'App Name'); ?></title>
	<link rel="stylesheet" href="<?php echo asset('/css/app.css'); ?>">
</head>
<body>
	<div class="container mt-5">
		<?php if (isset($_SESSION['error'])) : ?>
			<div class="alert alert-danger" role="alert">
				<?php echo $_SESSION['error']; ?>
			</div>
		<?php endif; ?>
		<form method="POST" action="?module=auth">
			<div class="form-floating mb-3">
				<input type="text" class="form-control" id="username" placeholder="Enter username" name="username" value="orangetiger142">
				<label for="username">Username</label>
			</div>
			<div class="form-floating mb-3">
				<input type="password" class="form-control" id="password" placeholder="Enter password" name="password" value="123">
				<label for="password">Password</label>
			</div>
			<div class="d-grid gap-2">
				<button class="btn btn-success btn-block" id="submit">Submit</button>
			</div>
		</form>
	</div>
</body>
</html>